project:
  title: "CounterfactualTraining.jl"
  execute-dir: project
  render:
    - "*.qmd"
    - "!docs/src/*.md"
crossref:
  fig-prefix: Figure
  tbl-prefix: Table 
  title-delim: 'space'
  exr-prefix: RQ
  exr-title: RQ
resource-path:
  - docs/src/assets
  - paper/figures
format:
  commonmark:
    variant: -raw_html+tex_math_dollars
    wrap: preserve
    mermaid-format: png
execute: 
  freeze: auto
  eval: true
  echo: false
  output: false
  daemon: 60
callout-icon: false
 
