name = "CounterfactualTraining"
uuid = "c5e5e904-ed0d-4ddb-967e-dbb7fd41a507"
authors = ["Patrick Altmeyer and contributors"]
version = "0.0.1"

[deps]
CounterfactualExplanations = "2f13d31b-18db-44c1-bc43-ebaf2cff0be0"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
TaijaParallel = "bf1c2c22-5e42-4e78-8b6b-92e6c673eeb0"

[compat]
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
