name = "CounterfactualTraining"
uuid = "c5e5e904-ed0d-4ddb-967e-dbb7fd41a507"
authors = ["Patrick Altmeyer and contributors"]
version = "0.0.1"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
CounterfactualExplanations = "2f13d31b-18db-44c1-bc43-ebaf2cff0be0"
EnergySamplers = "f446124b-5d5e-4171-a6dd-a1d99768d3ce"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TaijaParallel = "bf1c2c22-5e42-4e78-8b6b-92e6c673eeb0"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
Aqua = "0.8"
ChainRulesCore = "1.25"
CounterfactualExplanations = "1.3"
EnergySamplers = "1.0"
Flux = "0.14"
JLD2 = "0.4, 0.5"
StatsBase = "0.34"
TaijaParallel = "1.0, 1.1"
Test = "1"
UnicodePlots = "3.7"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
