grid_file = "grid_config.toml"
test_time = false
save_dir = "evaluation/evaluation_4"

[counterfactual_params]
threaded = false
maxiter = 100
store_ce = true
verbose = true
n_individuals = 100
n_runs = 1
vertical_splits = 100
parallelizer = "mpi"
conv = "max_iter"
concatenate_output = true

    [counterfactual_params.generator_params]
    opt = "sgd"
    lambda_cost = 0.001
    lr = 1.0
    maxiter = 50
    lambda_energy = 5.0
    type = "ECCo"
